### ISSUE TITLE
BouncyCheckbox fill color is not customizable

### ISSUE THREAD

**Issue by Ebaneck** [WrathChaos/react-native-multiple-select#2]
Hi,

Please can you make the Checkbox fill color customizable?

I see that the `doneButtonBackgroundColor` can be changed and it will be nice to
have something similar for the checkbox fill color.

Something like `menuItemCheckboxFillColor` :)

Best,

**Comment by kuraydev** [comment]
Hello @Ebaneck,

Sure I can make it :) I will inform you

**Comment by kuraydev** [comment]
Hey again @Ebaneck,
There is already a way to make this possible with prop drilling. You can use any prop from [react-native-bouncy-checkbox](https://github.com/WrathChaos/react-native-bouncy-checkbox). 

Simply try to use `fillColor` and you can customize the checkbox like that. There is no restriction for that.

**Comment by Ebaneck** [comment]
Hello @WrathChaos, indeed `fillColor` works just fine.

Thanks for the heads-up!
