### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSpinkit" was not found in the UIManager.

### ISSUE THREAD

**Issue by Ebaneck** [WrathChaos/react-native-multiple-select#3]
Hello,

It seems this library crashes on expo with the following error: Invariant Violation: requireNativeComponent: "RNSpinkit" was not found in the UIManager.

How to produce:
- Install the lib and its dependencies
- Try to delete the placeholder text.
- Boom!, you will get the crash.

Dev env:

```

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.44 
      expo: ^39.0.5 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: managed

```

Hacky proposal:
Maybe provide an option to disable text entry(typing) in the TextInput section since on Expo managed projects, RNSpinkit is not really supported.

**Comment by kuraydev** [comment]
Hello @Ebaneck,
I released a new version: 
## [Release 0.3.0](https://github.com/WrathChaos/react-native-multiple-select/releases/tag/0.3.0)

Please check it out, `react-native-spinkit` is removed and `react-native-animated-spinkit` is added instead.

**Comment by Ebaneck** [comment]
Thanks @WrathChaos it works great!
